const message = {
    AUTH: {
        LOGIN_SUCCESS: "Đăng nhập thành công",
        LOGIN_FAIL: "Đăng nhập thất bại",
        REGISTER_SUCCESS: "Đăng ký thành công",
        REGISTER_FAIL: "Đăng ký thất bại",
        LOGOUT_SUCCESS: "Đăng xuất thành công",
        LOGOUT_FAIL: "Đăng xuất thất bại",
        USER_NOT_FOUND: "Người dùng không tồn tại",
        USER_EXIST: "Người dùng đã tồn tại",
        PASSWORD_NOT_MATCH: "Mật khẩu không đúng",
        PASSWORD_MATCH: "Mật khẩu đúng",
        TOKEN_NOT_FOUND: "Token không tồn tại",
        TOKEN_EXPIRED: "Token đã hết hạn",
        TOKEN_INVALID: "Token không hợp lệ",
        TOKEN_VALID: "Token hợp lệ",
        TOKEN_REFRESH_SUCCESS: "Refresh token thành công",
        TOKEN_REFRESH_FAIL: "Refresh token thất bại",
        TOKEN_REFRESH_EXPIRED: "Refresh token đã hết hạn",
        TOKEN_REFRESH_INVALID: "Refresh token không hợp lệ",
        TOKEN_REFRESH_VALID: "Refresh token hợp lệ",
        TOKEN_REFRESH_NOT_FOUND: "Refresh token không tồn tại",
        TOKEN_REFRESH_EXIST: "Refresh token đã tồn tại",
        TOKEN_REFRESH_NOT_MATCH: "Refresh token không đúng",
        CREDENTIALS_REQUIRED: "Email và mật khẩu là bắt buộc",
        INVALID_CREDENTIALS: "Email hoặc mật khẩu không đúng",
        ACCOUNT_NOT_VERIFIED: "Tài khoản chưa được xác thực. Vui lòng kiểm tra email để xác thực tài khoản.",
        REGISTER_FIELDS_REQUIRED: "Họ tên, email, mật khẩu và xác nhận mật khẩu là bắt buộc",
        PASSWORD_CONFIRM_NOT_MATCH: "Mật khẩu và xác nhận mật khẩu không khớp",
        EMAIL_IN_USE: "Email này đã được sử dụng",
        INVALID_EMAIL: "Email không hợp lệ",
        PASSWORD_TOO_SHORT: "Mật khẩu phải có ít nhất 6 ký tự",
        INVALID_PHONE: "Số điện thoại không hợp lệ",
        REGISTER_SUCCESS_WITH_VERIFICATION: "Đăng ký tài khoản thành công. Vui lòng kiểm tra email để xác thực tài khoản.",
        REGISTER_SUCCESS_WITHOUT_VERIFICATION: "Đăng ký tài khoản thành công nhưng không thể gửi email xác thực.",
        INVALID_VERIFICATION_TOKEN: "Mã xác thực không hợp lệ hoặc đã hết hạn",
        USER_ACCOUNT_NOT_FOUND: "Không tìm thấy tài khoản người dùng",
        EMAIL_VERIFICATION_SUCCESS: "Xác thực email thành công",
        EMAIL_REQUIRED: "Email là bắt buộc",
        EMAIL_NOT_FOUND: "Không tìm thấy tài khoản với email này",
        RESET_EMAIL_SENT: "Email đặt lại mật khẩu đã được gửi",
        RESET_EMAIL_FAILED: "Không thể gửi email đặt lại mật khẩu",
        INVALID_RESET_TOKEN: "Token đặt lại mật khẩu không hợp lệ hoặc đã hết hạn",
        RESET_TOKEN_VALID: "Token hợp lệ",
        PASSWORD_FIELDS_REQUIRED: "Mật khẩu và xác nhận mật khẩu là bắt buộc",
        PASSWORD_RESET_SUCCESS: "Mật khẩu đã được đặt lại thành công",
        NOT_LOGGED_IN: "Bạn chưa đăng nhập"
    },
    USER: {
        GET_ALL_SUCCESS: "Lấy danh sách người dùng thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin người dùng thành công",
        CREATE_SUCCESS: "Tạo người dùng mới thành công",
        UPDATE_SUCCESS: "Cập nhật người dùng thành công",
        DELETE_SUCCESS: "Xóa người dùng thành công",
        CHANGE_ROLE_SUCCESS: "Thay đổi vai trò người dùng thành công",
        NOT_FOUND: "Không tìm thấy người dùng",
        EMAIL_IN_USE: "Email này đã được sử dụng",
        INVALID_ROLE: "Vai trò không hợp lệ",
        INVALID_ID: "ID người dùng không hợp lệ"
    },
    PRODUCT: {
        GET_ALL_SUCCESS: "Lấy danh sách sản phẩm thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách sản phẩm đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin sản phẩm thành công",
        CREATE_SUCCESS: "Tạo sản phẩm mới thành công",
        UPDATE_SUCCESS: "Cập nhật sản phẩm thành công",
        DELETE_SUCCESS: "Xóa sản phẩm thành công",
        RESTORE_SUCCESS: "Khôi phục sản phẩm thành công",
        NOT_FOUND: "Không tìm thấy sản phẩm",
        INVALID_ID: "ID sản phẩm không hợp lệ",
        NAME_REQUIRED: "Tên sản phẩm là bắt buộc",
        NAME_TOO_LONG: "Tên sản phẩm không được vượt quá 100 ký tự",
        PRICE_REQUIRED: "Giá sản phẩm là bắt buộc",
        PRICE_INVALID: "Giá sản phẩm phải là số dương",
        STOCK_INVALID: "Số lượng tồn kho phải là số không âm",
        CATEGORY_ID_INVALID: "ID danh mục không hợp lệ",
        COLOR_ID_INVALID: "ID màu sắc không hợp lệ",
        STORAGE_ID_INVALID: "ID bộ nhớ không hợp lệ",
        IMAGE_URL_TOO_LONG: "URL hình ảnh không được vượt quá 255 ký tự",
        ALREADY_DELETED: "Sản phẩm này đã bị xóa trước đó",
        NOT_DELETED: "Sản phẩm này chưa bị xóa",
        INVALID_STATUS: "Trạng thái không hợp lệ",
        UPDATE_STATUS_SUCCESS: "Cập nhật trạng thái sản phẩm thành công",
        SEARCH_REQUIRED: "Từ khóa tìm kiếm là bắt buộc",
        SEARCH_SUCCESS: "Tìm kiếm sản phẩm thành công"
    },
    PRODUCT_COLOR: {
        GET_ALL_SUCCESS: "Lấy danh sách màu sắc thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách màu sắc đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin màu sắc thành công",
        CREATE_SUCCESS: "Tạo màu sắc mới thành công",
        UPDATE_SUCCESS: "Cập nhật màu sắc thành công",
        DELETE_SUCCESS: "Xóa màu sắc thành công",
        RESTORE_SUCCESS: "Khôi phục màu sắc thành công",
        NOT_FOUND: "Không tìm thấy màu sắc",
        INVALID_ID: "ID màu sắc không hợp lệ",
        NAME_PRICE_REQUIRED: "Tên và giá màu sắc là bắt buộc",
        NAME_TOO_LONG: "Tên màu sắc không được vượt quá 100 ký tự",
        PRICE_INVALID: "Giá phải là số không âm",
        ALREADY_DELETED: "Màu sắc này đã bị xóa trước đó",
        NOT_DELETED: "Màu sắc này chưa bị xóa"
    },
    PRODUCT_STORAGE: {
        GET_ALL_SUCCESS: "Lấy danh sách dung lượng thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách dung lượng đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin dung lượng thành công",
        CREATE_SUCCESS: "Tạo dung lượng mới thành công",
        UPDATE_SUCCESS: "Cập nhật dung lượng thành công",
        DELETE_SUCCESS: "Xóa dung lượng thành công",
        RESTORE_SUCCESS: "Khôi phục dung lượng thành công",
        NOT_FOUND: "Không tìm thấy dung lượng",
        INVALID_ID: "ID dung lượng không hợp lệ",
        NAME_PRICE_REQUIRED: "Tên và giá dung lượng là bắt buộc",
        NAME_TOO_LONG: "Tên dung lượng không được vượt quá 100 ký tự",
        PRICE_INVALID: "Giá phải là số không âm",
        ALREADY_DELETED: "Dung lượng này đã bị xóa trước đó",
        NOT_DELETED: "Dung lượng này chưa bị xóa"
    },
    CATEGORY: {
        GET_ALL_SUCCESS: "Lấy danh sách danh mục thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách danh mục đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin danh mục thành công",
        CREATE_SUCCESS: "Tạo danh mục mới thành công",
        UPDATE_SUCCESS: "Cập nhật danh mục thành công",
        DELETE_SUCCESS: "Xóa danh mục thành công",
        RESTORE_SUCCESS: "Khôi phục danh mục thành công",
        NOT_FOUND: "Không tìm thấy danh mục",
        INVALID_ID: "ID danh mục không hợp lệ",
        NAME_REQUIRED: "Tên danh mục là bắt buộc",
        NAME_TOO_LONG: "Tên danh mục không được vượt quá 50 ký tự",
        ALREADY_EXISTS: "Danh mục này đã tồn tại",
        ALREADY_DELETED: "Danh mục này đã bị xóa trước đó",
        NOT_DELETED: "Danh mục này chưa bị xóa",
        CANNOT_UPDATE_DELETED: "Không thể cập nhật danh mục đã bị xóa"
    },
    BANNER: {
        GET_ALL_SUCCESS: "Lấy danh sách banner thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách banner đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin banner thành công",
        CREATE_SUCCESS: "Tạo banner mới thành công",
        UPDATE_SUCCESS: "Cập nhật banner thành công",
        DELETE_SUCCESS: "Xóa banner thành công",
        RESTORE_SUCCESS: "Khôi phục banner thành công",
        TOGGLE_STATUS_SUCCESS: "Thay đổi trạng thái banner thành công",
        NOT_FOUND: "Không tìm thấy banner",
        INVALID_ID: "ID banner không hợp lệ",
        IMAGE_URL_REQUIRED: "URL hình ảnh là bắt buộc",
        TITLE_TOO_LONG: "Tiêu đề không được vượt quá 100 ký tự",
        IMAGE_URL_TOO_LONG: "URL hình ảnh không được vượt quá 255 ký tự",
        LINK_URL_TOO_LONG: "URL liên kết không được vượt quá 255 ký tự",
        POSITION_TOO_LONG: "Vị trí không được vượt quá 50 ký tự",
        ALREADY_DELETED: "Banner này đã bị xóa trước đó",
        NOT_DELETED: "Banner này chưa bị xóa",
        CANNOT_UPDATE_DELETED: "Không thể cập nhật banner đã bị xóa"
    },
    REVIEW: {
        GET_ALL_SUCCESS: "Lấy danh sách đánh giá thành công",
    },
    CART: {
        ADD_SUCCESS: "Thêm sản phẩm vào giỏ hàng thành công",
        GET_SUCCESS: "Lấy thông tin giỏ hàng thành công",
        UPDATE_SUCCESS: "Cập nhật giỏ hàng thành công",
        DELETE_SUCCESS: "Xóa giỏ hàng thành công",
        CLEAR_SUCCESS: "Xóa toàn bộ sản phẩm trong giỏ hàng thành công",
        PRODUCT_NOT_FOUND: "Sản phẩm không tồn tại trong giỏ hàng",
        OUT_OF_STOCK: "Sản phẩm đã hết hàng",
        INVALID_QUANTITY: "Số lượng không hợp lệ"
    },
    ORDER: {
        CREATE_SUCCESS: "Tạo đơn hàng thành công",
        GET_LIST_SUCCESS: "Lấy danh sách đơn hàng thành công",
        GET_DETAIL_SUCCESS: "Lấy chi tiết đơn hàng thành công",
        GET_ALL_SUCCESS: "Lấy danh sách tất cả đơn hàng thành công",
        UPDATE_STATUS_SUCCESS: "Cập nhật trạng thái đơn hàng thành công",
        CANCEL_SUCCESS: "Hủy đơn hàng thành công",
        CART_EMPTY: "Giỏ hàng trống",
        PRODUCT_NOT_FOUND: "Sản phẩm không tồn tại",
        NOT_FOUND: "Đơn hàng không tồn tại",
        CANNOT_CANCEL: "Không thể hủy đơn hàng đã được xử lý",
        INVALID_STATUS_TRANSITION: "Không thể chuyển từ trạng thái này sang trạng thái khác",
        OUT_OF_STOCK: (productName, stock) => `Sản phẩm ${productName} chỉ còn ${stock} trong kho`
    },
    PAYMENT: {
        ORDER_NOT_FOUND: "Đơn hàng không tồn tại",
        ALREADY_PAID: "Đơn hàng đã được thanh toán",
        CANNOT_PAY_CANCELLED: "Không thể thanh toán đơn hàng đã hủy",
        INVALID_METHOD: "Phương thức thanh toán không hợp lệ",
        SUCCESS: "Thanh toán thành công",
        FAILED: "Thanh toán thất bại",
        ERROR: "Có lỗi xảy ra trong quá trình thanh toán",
        BANK_INFO_REQUIRED: "Thông tin chuyển khoản không đầy đủ",
        BANK_TRANSACTION_INVALID: "Giao dịch chuyển khoản không hợp lệ",
        CARD_INFO_REQUIRED: "Thông tin thẻ không đầy đủ",
        CARD_INVALID: "Thông tin thẻ không hợp lệ",
        MOMO_INFO_REQUIRED: "Thông tin thanh toán MoMo không đầy đủ",
        MOMO_OTP_INVALID: "Mã OTP không hợp lệ",
        HISTORY_SUCCESS: "Lấy lịch sử thanh toán thành công",
        REFUND_ONLY_PAID: "Chỉ có thể hoàn tiền đơn hàng đã thanh toán",
        REFUND_DELIVERED: "Không thể hoàn tiền đơn hàng đã giao",
        REFUND_SUCCESS: "Hoàn tiền thành công",
        REFUND_FAILED: "Hoàn tiền thất bại"
    },
    DISCOUNT: {
        GET_ALL_SUCCESS: "Lấy danh sách giảm giá thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin giảm giá thành công",
        CREATE_SUCCESS: "Tạo giảm giá mới thành công",
        UPDATE_SUCCESS: "Cập nhật giảm giá thành công",
        DELETE_SUCCESS: "Xóa giảm giá thành công",
        NOT_FOUND: "Không tìm thấy giảm giá",
        INVALID_ID: "ID giảm giá không hợp lệ",
        PRODUCT_NOT_FOUND: "Sản phẩm không tồn tại",
        INVALID_DISCOUNT_VALUE: "Giá trị giảm giá không hợp lệ",
        INVALID_DATE_RANGE: "Ngày kết thúc phải sau ngày bắt đầu",
        PERCENTAGE_EXCEED_100: "Phần trăm giảm giá không được vượt quá 100%",
        ADD_PRODUCTS_SUCCESS: "Thêm sản phẩm vào giảm giá thành công",
        REMOVE_PRODUCTS_SUCCESS: "Xóa sản phẩm khỏi giảm giá thành công",
        PRODUCTS_REQUIRED: "Danh sách sản phẩm là bắt buộc",
        PRODUCTS_NOT_FOUND: "Một số sản phẩm không tồn tại"
    }
};

export default message;