const message = {
    AUTH: {
        LOGIN_SUCCESS: "Đăng nhập thành công",
        LOGIN_FAIL: "Đăng nhập thất bại",
        REGISTER_SUCCESS: "Đăng ký thành công",
        REGISTER_FAIL: "Đăng ký thất bại",
        LOGOUT_SUCCESS: "Đăng xuất thành công",
        LOGOUT_FAIL: "Đăng xuất thất bại",
        USER_NOT_FOUND: "Người dùng không tồn tại",
        USER_EXIST: "Người dùng đã tồn tại",
        PASSWORD_NOT_MATCH: "Mật khẩu không đúng",
        PASSWORD_MATCH: "Mật khẩu đúng",
        TOKEN_NOT_FOUND: "Token không tồn tại",
        TOKEN_EXPIRED: "Token đã hết hạn",
        TOKEN_INVALID: "Token không hợp lệ",
        TOKEN_VALID: "Token hợp lệ",
        TOKEN_REFRESH_SUCCESS: "Refresh token thành công",
        TOKEN_REFRESH_FAIL: "Refresh token thất bại",
        TOKEN_REFRESH_EXPIRED: "Refresh token đã hết hạn",
        TOKEN_REFRESH_INVALID: "Refresh token không hợp lệ",
        TOKEN_REFRESH_VALID: "Refresh token hợp lệ",
        TOKEN_REFRESH_NOT_FOUND: "Refresh token không tồn tại",
        TOKEN_REFRESH_EXIST: "Refresh token đã tồn tại",
        TOKEN_REFRESH_NOT_MATCH: "Refresh token không đúng",
        CREDENTIALS_REQUIRED: "Email và mật khẩu là bắt buộc",
        INVALID_CREDENTIALS: "Email hoặc mật khẩu không đúng",
        ACCOUNT_NOT_VERIFIED: "Tài khoản chưa được xác thực. Vui lòng kiểm tra email để xác thực tài khoản.",
        REGISTER_FIELDS_REQUIRED: "Họ tên, email, mật khẩu và xác nhận mật khẩu là bắt buộc",
        PASSWORD_CONFIRM_NOT_MATCH: "Mật khẩu và xác nhận mật khẩu không khớp",
        EMAIL_IN_USE: "Email này đã được sử dụng",
        INVALID_EMAIL: "Email không hợp lệ",
        PASSWORD_TOO_SHORT: "Mật khẩu phải có ít nhất 6 ký tự",
        INVALID_PHONE: "Số điện thoại không hợp lệ",
        REGISTER_SUCCESS_WITH_VERIFICATION: "Đăng ký tài khoản thành công. Vui lòng kiểm tra email để xác thực tài khoản.",
        REGISTER_SUCCESS_WITHOUT_VERIFICATION: "Đăng ký tài khoản thành công nhưng không thể gửi email xác thực.",
        INVALID_VERIFICATION_TOKEN: "Mã xác thực không hợp lệ hoặc đã hết hạn",
        USER_ACCOUNT_NOT_FOUND: "Không tìm thấy tài khoản người dùng",
        EMAIL_VERIFICATION_SUCCESS: "Xác thực email thành công",
        EMAIL_REQUIRED: "Email là bắt buộc",
        EMAIL_NOT_FOUND: "Không tìm thấy tài khoản với email này",
        RESET_EMAIL_SENT: "Email đặt lại mật khẩu đã được gửi",
        RESET_EMAIL_FAILED: "Không thể gửi email đặt lại mật khẩu",
        INVALID_RESET_TOKEN: "Token đặt lại mật khẩu không hợp lệ hoặc đã hết hạn",
        RESET_TOKEN_VALID: "Token hợp lệ",
        PASSWORD_FIELDS_REQUIRED: "Mật khẩu và xác nhận mật khẩu là bắt buộc",
        PASSWORD_RESET_SUCCESS: "Mật khẩu đã được đặt lại thành công",
        NOT_LOGGED_IN: "Bạn chưa đăng nhập"
    },
    PRODUCT: {
        GET_ALL_SUCCESS: "Lấy danh sách sản phẩm thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách sản phẩm đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin sản phẩm thành công",
        CREATE_SUCCESS: "Tạo sản phẩm mới thành công",
        UPDATE_SUCCESS: "Cập nhật sản phẩm thành công",
        DELETE_SUCCESS: "Xóa sản phẩm thành công",
        RESTORE_SUCCESS: "Khôi phục sản phẩm thành công",
        NOT_FOUND: "Không tìm thấy sản phẩm",
        INVALID_ID: "ID sản phẩm không hợp lệ",
        NAME_REQUIRED: "Tên sản phẩm là bắt buộc",
        NAME_TOO_LONG: "Tên sản phẩm không được vượt quá 100 ký tự",
        PRICE_REQUIRED: "Giá sản phẩm là bắt buộc",
        PRICE_INVALID: "Giá sản phẩm phải là số dương",
        STOCK_INVALID: "Số lượng tồn kho phải là số không âm",
        CATEGORY_ID_INVALID: "ID danh mục không hợp lệ",
        COLOR_ID_INVALID: "ID màu sắc không hợp lệ",
        STORAGE_ID_INVALID: "ID bộ nhớ không hợp lệ",
        IMAGE_URL_TOO_LONG: "URL hình ảnh không được vượt quá 255 ký tự",
        ALREADY_DELETED: "Sản phẩm này đã bị xóa trước đó",
        NOT_DELETED: "Sản phẩm này chưa bị xóa"
    },
    PRODUCT_COLOR: {
        GET_ALL_SUCCESS: "Lấy danh sách màu sắc thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách màu sắc đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin màu sắc thành công",
        CREATE_SUCCESS: "Tạo màu sắc mới thành công",
        UPDATE_SUCCESS: "Cập nhật màu sắc thành công",
        DELETE_SUCCESS: "Xóa màu sắc thành công",
        RESTORE_SUCCESS: "Khôi phục màu sắc thành công",
        NOT_FOUND: "Không tìm thấy màu sắc",
        INVALID_ID: "ID màu sắc không hợp lệ",
        NAME_PRICE_REQUIRED: "Tên và giá màu sắc là bắt buộc",
        NAME_TOO_LONG: "Tên màu sắc không được vượt quá 100 ký tự",
        PRICE_INVALID: "Giá phải là số không âm",
        ALREADY_DELETED: "Màu sắc này đã bị xóa trước đó",
        NOT_DELETED: "Màu sắc này chưa bị xóa"
    },
    PRODUCT_STORAGE: {
        GET_ALL_SUCCESS: "Lấy danh sách dung lượng thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách dung lượng đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin dung lượng thành công",
        CREATE_SUCCESS: "Tạo dung lượng mới thành công",
        UPDATE_SUCCESS: "Cập nhật dung lượng thành công",
        DELETE_SUCCESS: "Xóa dung lượng thành công",
        RESTORE_SUCCESS: "Khôi phục dung lượng thành công",
        NOT_FOUND: "Không tìm thấy dung lượng",
        INVALID_ID: "ID dung lượng không hợp lệ",
        NAME_PRICE_REQUIRED: "Tên và giá dung lượng là bắt buộc",
        NAME_TOO_LONG: "Tên dung lượng không được vượt quá 100 ký tự",
        PRICE_INVALID: "Giá phải là số không âm",
        ALREADY_DELETED: "Dung lượng này đã bị xóa trước đó",
        NOT_DELETED: "Dung lượng này chưa bị xóa"
    },
    CATEGORY: {
        GET_ALL_SUCCESS: "Lấy danh sách danh mục thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách danh mục đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin danh mục thành công",
        CREATE_SUCCESS: "Tạo danh mục mới thành công",
        UPDATE_SUCCESS: "Cập nhật danh mục thành công",
        DELETE_SUCCESS: "Xóa danh mục thành công",
        RESTORE_SUCCESS: "Khôi phục danh mục thành công",
        NOT_FOUND: "Không tìm thấy danh mục",
        INVALID_ID: "ID danh mục không hợp lệ",
        NAME_REQUIRED: "Tên danh mục là bắt buộc",
        NAME_TOO_LONG: "Tên danh mục không được vượt quá 50 ký tự",
        ALREADY_EXISTS: "Danh mục này đã tồn tại",
        ALREADY_DELETED: "Danh mục này đã bị xóa trước đó",
        NOT_DELETED: "Danh mục này chưa bị xóa",
        CANNOT_UPDATE_DELETED: "Không thể cập nhật danh mục đã bị xóa"
    },
    BANNER: {
        GET_ALL_SUCCESS: "Lấy danh sách banner thành công",
        GET_TRASHED_SUCCESS: "Lấy danh sách banner đã xóa mềm thành công",
        GET_BY_ID_SUCCESS: "Lấy thông tin banner thành công",
        CREATE_SUCCESS: "Tạo banner mới thành công",
        UPDATE_SUCCESS: "Cập nhật banner thành công",
        DELETE_SUCCESS: "Xóa banner thành công",
        RESTORE_SUCCESS: "Khôi phục banner thành công",
        TOGGLE_STATUS_SUCCESS: "Thay đổi trạng thái banner thành công",
        NOT_FOUND: "Không tìm thấy banner",
        INVALID_ID: "ID banner không hợp lệ",
        IMAGE_URL_REQUIRED: "URL hình ảnh là bắt buộc",
        TITLE_TOO_LONG: "Tiêu đề không được vượt quá 100 ký tự",
        IMAGE_URL_TOO_LONG: "URL hình ảnh không được vượt quá 255 ký tự",
        LINK_URL_TOO_LONG: "URL liên kết không được vượt quá 255 ký tự",
        POSITION_TOO_LONG: "Vị trí không được vượt quá 50 ký tự",
        ALREADY_DELETED: "Banner này đã bị xóa trước đó",
        NOT_DELETED: "Banner này chưa bị xóa",
        CANNOT_UPDATE_DELETED: "Không thể cập nhật banner đã bị xóa"
    },
    REVIEW: {
        GET_ALL_SUCCESS: "Lấy danh sách đánh giá thành công",
    }
};

export default message;